### ISSUE TITLE
 TypeError: Patterns must be a string or an array of strings

### ISSUE THREAD

**Issue by bluedusk** [postcss/postcss-cli#212]
Got this error: 
>    TypeError: Patterns must be a string or an array of strings

Error Message Detail:

```
TypeError: Patterns must be a string or an array of strings
    at assertPatternsInput (D:\WorkSpace\CSS\css_advance_course\Natours\starter\node_modules\globby\index.js:15:9)
    at generateGlobTasks (D:\WorkSpace\CSS\css_advance_course\Natours\starter\node_modules\globby\index.js:21:2)
    at module.exports (D:\WorkSpace\CSS\css_advance_course\Natours\starter\node_modules\globby\index.js:73:15)
    at Promise.resolve.then (D:\WorkSpace\CSS\css_advance_course\Natours\starter\node_modules\postcss-cli\index.js:55:39)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
    at Function.Module.runMain (module.js:695:11)
    at startup (bootstrap_node.js:188:16)
    at bootstrap_node.js:609:3
```

When I try to run this with npm script:

>    "postcss --use autoprefixer -b 'last 10 versions' input.css -o output.css"

System Environment:
>     
    System: Win7 64
    Node: v8.11.1
    NPM: 5.6.0
    "autoprefixer": "^8.4.1",
    "postcss-cli": "^5.0.0"

**Comment by RyanZim** [comment]
postcss-cli doesn't have an option `-b`; you'll want to either use a config file, or keep your browserslist config in your package.json

**Comment by m-waqas-a** [comment]
postcss --use autoprefixer -b \"last 10 versions\" a.css -o b.css

**Comment by rdhammack88** [comment]
For those of you still having this problem and are using windows, try this link as it worked for me.
[Answer](https://github.com/npm/npm/issues/20048). Basically, instead of using single quotes, use double quotes around the \"last 10 versions\" and escape the quotes.

**Comment by TopzTheDev** [comment]
try this mate 💯 
postcss --use autoprefixer -b \"last 10 versions\" resources/css/style.concat.css -o resources/css/style.prefix.css

**Comment by mdrsahal** [comment]
> For those of you still having this problem and are using windows, try this link as it worked for me.
> [Answer](https://github.com/npm/npm/issues/20048). Basically, instead of using single quotes, use double quotes around the "last 10 versions" and escape the quotes.

 
it worked. thank you.
