### ISSUE TITLE
The "path" argument must be of type string. Received type undefined

### ISSUE THREAD

**Issue by manuelmazzuola** [postcss/postcss-cli#261]
The following `node_modules/postcss-cli/bin/postcss --include-dotfiles -o ./build/styles/marketplace-blue.css ./app/styles/marketplace.css` throws 
```
TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received type undefined                   
    at assertPath (path.js:39:11)
    at Object.join (path.js:1152:7)
    at getPath (/home/originof/src/marketplace/node_modules/dir-glob/index.js:6:41)                                     
    at Promise.all.concat.map.x (/home/originof/src/marketplace/node_modules/dir-glob/index.js:39:60)                   
    at Array.map (<anonymous>)
    at module.exports (/home/originof/src/marketplace/node_modules/dir-glob/index.js:39:38)                             
    at globDirs (/home/originof/src/marketplace/node_modules/globby/index.js:58:9)                                      
    at getPattern (/home/originof/src/marketplace/node_modules/globby/index.js:61:64)                                   
    at Promise.all.globTasks.map.task (/home/originof/src/marketplace/node_modules/globby/index.js:72:69)               
    at Array.map (<anonymous>)
```

postcss-cli 6.1.1
node 10.15.0

Following a PR to fix the issue.

**Comment by manuelmazzuola** [comment]
Issue fixed in globby https://github.com/sindresorhus/globby/pull/99#issuecomment-452647305
