### ISSUE TITLE
Hi， When I install the latest version of postcss and autoprefixer, I perform “npx postcss *.css --use autoprefixer -d build/”

### ISSUE THREAD

**Issue by xiaoqiang007-github** [postcss/postcss-cli#411]
hi

C:\Users\xxx190\Desktop\test\node_modules\postcss-cli\index.js:3
import fs from 'fs-extra'
       ^^

SyntaxError: Unexpected identifier
    at Module._compile (internal/modules/cjs/loader.js:723:23)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:623:3)

**Comment by RyanZim** [comment]
Looks like you're using an old version of Node.js. postcss-cli requires Node v12 or higher.

**Comment by abelardogit** [comment]
Hi there!
I am using node v20.18.0 and I see this same error. 
Just installed.
