### ISSUE TITLE
npm script fails with "SyntaxError: Cannot use import statement outside a module"

### ISSUE THREAD

**Issue by uluhonolulu** [postcss/postcss-cli#419]
I'm trying to run postcss on my Windows system with NodeJS 12.14. I'm consistently getting "SyntaxError: Cannot use import statement outside a module".

Here's the full output:
```
PS C:\Emr\Tools\bootstrap> node -v
v12.14.0

PS C:\Emr\Tools\bootstrap> postcss --config build/postcss.config.js --replace "dist/css/*.css" "!dist/css/*.min.css"
C:\Users\uluho\AppData\Roaming\npm\node_modules\postcss-cli\index.js:3
import fs from 'fs-extra'
^^^^^^

SyntaxError: Cannot use import statement outside a module
    at Module._compile (internal/modules/cjs/loader.js:895:18)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:995:10)
    at Module.load (internal/modules/cjs/loader.js:815:32)
    at Function.Module._load (internal/modules/cjs/loader.js:727:14)
    at Function.Module.runMain (internal/modules/cjs/loader.js:1047:10)
    at internal/main/run_main_module.js:17:11
```

**Comment by RyanZim** [comment]
You need to use Node 12.17+ to support ESM modules without a flag, which postcss-cli uses.
